{% set name = "azure-batch" %}
{% set version = "14.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure-batch-{{ version }}.tar.gz
  sha256: c79267d6c3d3fe14a16a422ab5bbfabcbd68ed0b58b6bbcdfa0c8345c4c78532

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - msrestazure >=0.4.32,<2.0.0
    - azure-common >=1.1,<2.dev0

test:
  imports:
    - azure.batch
    - azure.batch.custom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Batch Client Library for Python
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://docs.microsoft.com/en-us/azure/developer/python/
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - xylar
